# NumPy Overview

In [2]:
import numpy as np

**1. Initializing NumPy Array**

1.1. With a list

In [20]:
list=[1, 2, 4, 5]
arr1=np.array(list)
arr2=np.array([1, 2, 4, 5])
print(arr1, arr2)

[1 2 4 5] [1 2 4 5]


1.2. With np.ones and np.zeros

In [21]:
arr3=np.ones(4)
arr4=np.zeros(4)
print(arr3, arr4)

[1. 1. 1. 1.] [0. 0. 0. 0.]


1.3. With np.full and np.empty

In [24]:
arr5=np.full(4, 6)
arr6=np.empty(8)
print(arr5, arr6, sep='\n')

[6 6 6 6]
[0.000e+000 0.000e+000 0.000e+000 0.000e+000 0.000e+000 4.704e-321
 0.000e+000 0.000e+000]


1.4. With np.arange

In [29]:
arr7=np.arange(2, 5, 2) # could also use only one or two arguments
print(arr7)

[2 4]


1.5. With np.random.rand

In [31]:
arr8=np.random.rand(5)
print(arr8)

[0.97551868 0.6028303  0.63522196 0.36880068 0.10116804]


**2. Initializing ND Array**

2.1. With lists

In [40]:
arr2d=np.array([[1, 2],
               [3, 4]])
arr3d=np.array([[[1, 2],
        [3, 4]],
        
        [[5, 6],
        [7, 8]]])

print(arr2d, arr3d, sep='\n'*2)

[[1 2]
 [3 4]]

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


2.2. With np.ones and np.zeros

In [54]:
arro2d=np.ones((4, 3))
arrz3d=np.zeros((4,4,4))
print(arro2d, arrz3d, sep='\n'*3)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


2.3. With np.empty and np.full

In [59]:
arre3d=np.empty((3,3,3))
arrf3d=np.full((3,3,3), 3)
print(arre3d, arrf3d, sep='\n'*2)

[[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
  [1.33511018e-306 4.45060607e-308 9.34597567e-307]
  [1.42419938e-306 7.56603881e-307 8.45603440e-307]]

 [[3.56043054e-307 1.60219306e-306 6.23059726e-307]
  [1.06811422e-306 3.56043054e-307 1.37961641e-306]
  [1.00132483e-307 8.01097889e-307 1.78020169e-306]]

 [[7.56601165e-307 1.02359984e-306 1.33510679e-306]
  [2.22522597e-306 1.60220393e-306 1.86921143e-306]
  [1.11261434e-306 2.22522596e-306 2.56765117e-312]]]

[[[3 3 3]
  [3 3 3]
  [3 3 3]]

 [[3 3 3]
  [3 3 3]
  [3 3 3]]

 [[3 3 3]
  [3 3 3]
  [3 3 3]]]


2.4. With np.random.rand

In [60]:
arrr3d=np.random.rand(3,3,3)
print(arrr3d)

[[[0.00492382 0.90384186 0.79904409]
  [0.77583801 0.06913018 0.41474093]
  [0.12254323 0.5599702  0.12059434]]

 [[0.85041238 0.82987802 0.33327734]
  [0.01329156 0.50452156 0.49062027]
  [0.75351408 0.92832726 0.06913675]]

 [[0.84791734 0.76674462 0.3232996 ]
  [0.08505975 0.19478576 0.68362301]
  [0.76277293 0.02094927 0.26131866]]]


**3. Data Types**

3.1. Check data type

In [63]:
arrx=np.array([1,2,3,4])
print(arrx.dtype) # dtype attribute

int32


3.2. Specify data type

In [65]:
arry=np.array([1,2,3,4], dtype="int16") # dtype parameter
print(arry.dtype)

int16


3.3. Convert data type

In [72]:
arrz=arry.astype("float64")
print(arrz, arrz.dtype)

arra=np.array([1.44, 4.55, 6.88, 9.753])
arrb=arra.astype("complex64")
print(arrb, arrb.dtype)

[1. 2. 3. 4.] float64
[1.44 +0.j 4.55 +0.j 6.88 +0.j 9.753+0.j] complex64


**4. Array Attributes**

In [73]:
# Attributes provide information about the array

In [93]:
arrayxy=np.array([[1, 3, 4],
                  [4, 5, 9]])

4.1. ndim

In [94]:
print(arrayxy.ndim)

2


4.2. size

In [95]:
print(arrayxy.size)

6


4.3. shape

In [96]:
print(arrayxy.shape)

(2, 3)


4.4. dtype (as above)

In [97]:
print(arrayxy.dtype)

int32


4.5. itemsize

In [98]:
print(arrayxy.itemsize)

4


4.6. data

In [99]:
print(arrayxy.data)

**6. Array Functions**

6.1. Array Creation Functions


Already covered at 1.

6.2. Array Manipulation Functions

6.2.1. np.reshape

In [100]:
rarr=np.array([1,2,3,4,5,6,7,8])
arr2d=np.reshape(rarr,(4, 2))
arr3d=np.reshape(rarr,(2, 2, 2))

flattenarr=np.reshape([[1, 2], [3, 4], [5, 6],[7, 8]], -1)

print(arr2d, arr3d,flattenarr, sep="\n"*2)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

[1 2 3 4 5 6 7 8]


6.2.2. np.transpose (swaps axes) i

In [101]:
# does not work with 1D Array
transarr=np.array([[1, 2], 
                   [3, 4]])
# 3d Array Investigation
np.transpose(transarr)

array([[1, 3],
       [2, 4]])

6.3. Array Mathematical Functions

In [102]:
firstarr=np.array([8, 6, 4, 2])
secondarr=np.array([1, 2, 3, 4])

6.3.1. Addition

In [103]:
res1=firstarr + secondarr
res2=np.add(firstarr, secondarr)
print(res1, res2, sep="\n")

[9 8 7 6]
[9 8 7 6]


6.3.2. Subtraction

In [104]:
res3=firstarr - secondarr
res4=np.subtract(firstarr, secondarr)
print(res3, res4, sep="\n")

[ 7  4  1 -2]
[ 7  4  1 -2]


6.3.3. Multiplication

In [105]:
res5= firstarr * secondarr
res6=np.multiply(firstarr, secondarr)
print(res5, res6, sep="\n")

[ 8 12 12  8]
[ 8 12 12  8]


6.3.4. Division

In [106]:
res7=firstarr / secondarr
res8=np.divide(firstarr, secondarr)
print(res7, res8, sep="\n")

[8.         3.         1.33333333 0.5       ]
[8.         3.         1.33333333 0.5       ]


6.3.5. Exponentiation

In [107]:
res9= firstarr ** 2
res10=np.power(firstarr, 2)
print(res9, res10, sep="\n")

[64 36 16  4]
[64 36 16  4]


6.3.6. Modulus

In [108]:
res11=firstarr % secondarr
res12=np.mod(firstarr, secondarr)
print(res11, res12, sep="\n")

[0 0 1 2]
[0 0 1 2]


6.4. Array Statistical Functions

In [109]:
statsarr=np.array([2, 3, 4 , 5, 7, 8, 9])
statsarr2d=np.array([[1, 2],
                     [3, 4],
                     [5, 6]])

6.4.1. median  

In [110]:
med=np.median(statsarr)
print(med)

med2d=np.median(statsarr2d)
print(med2d)

medvertical2d=np.median(statsarr2d, axis=1)
print(medvertical2d)

medhorizontal2d=np.median(statsarr2d, axis=0)
print(medhorizontal2d)

5.0
3.5
[1.5 3.5 5.5]
[3. 4.]


6.4.2. mean i

In [111]:
mean=np.mean(statsarr)
print(mean)

mean2d=np.mean(statsarr2d)
print(mean2d)

meanvertical2d=np.mean(statsarr2d, axis=1)
print(meanvertical2d)

meanhorizontal2d=np.mean(statsarr2d, axis=0)
print(meanhorizontal2d)

5.428571428571429
3.5
[1.5 3.5 5.5]
[3. 4.]


6.4.3. std (standard deviation)

In [112]:
std=np.std(statsarr)
print(std)

std2d=np.std(statsarr2d)
print(std2d)

stdvertical2d=np.std(statsarr2d, axis=1)
print(stdvertical2d)

stdhorizontal2d=np.std(statsarr2d, axis=0)
print(stdhorizontal2d)

2.4411439272335804
1.707825127659933
[0.5 0.5 0.5]
[1.63299316 1.63299316]


6.4.4. percentile i

In [113]:
per=np.percentile(statsarr, 1)
print(per)

2.06


6.4.5. min and max i

In [114]:
min=np.min(statsarr)
max=np.max(statsarr)

print(min, max, sep="\n")

2
9


6.5. Array Input/Output Functions  i

**7. Math Functions**

7.1. Array Mathematical Functions

Already covered at 6.3.

7.2. Trigonometric Functions

7.2.1. sin, cos, tan

7.2.2. arsin, arcos, arctan

7.2.3. degrees, radians

7.3. Rounding Functions

In [115]:
num=np.array([5.333, 7.924, 6.832, 3.47])

7.3.1. round

In [116]:
round=np.round(num, 1)
print(round)

[5.3 7.9 6.8 3.5]


7.3.2. floor, ceil

In [117]:
fl=np.floor(num)
ce=np.ceil(num)
print(fl,ce, sep="\n")

[5. 7. 6. 3.]
[6. 8. 7. 4.]


**8. Constants**

8.1. pi

In [118]:
r=4
area_circle=np.pi * pow(r, 2)
print(area_circle)

50.26548245743669


8.2. e   (euler's number)

In [119]:
x=1
y=np.exp(x)
print(y)

2.718281828459045


**9. Comparison/Logical Operators (same as Python, only with Arrays)**

9.1. Logical Operators 

In [120]:
logicx1=np.array([0, True, False])
logicx2=np.array([False, False, 1])

9.1.1. Logical and

In [121]:
print(np.logical_and(logicx1, logicx2))

[False False False]


9.1.2. Logical or

In [122]:
print(np.logical_or(logicx1, logicx2))

[False  True  True]


9.1.3. Logical not

In [123]:
print(np.logical_not(logicx1))
print(np.logical_not(logicx2))

[ True False  True]
[ True  True False]


9.2. Comparison Operators i

In [124]:
array1=np.array([4, 8, 3])
array2=np.array([6, 8, 1])

9.2.1. Less than

In [125]:
outc1=np.less(array1, array2)
print(outc1)

outc2= array1 < array2
print(outc2)

[ True False False]
[ True False False]


9.2.2. Less than or equal to

In [126]:
outc3=np.less_equal(array1, array2)
print(outc3)

outc4= array1 <= array2
print(outc4)

[ True  True False]
[ True  True False]


9.2.3. Greater than

In [127]:
outc5=np.greater(array1, array2)
print(outc5)

outc6= array1 > array2
print(outc6)

[False False  True]
[False False  True]


9.2.4. Greater than or equal to

In [128]:
outc7=np.greater_equal(array1, array2)
print(outc7)

outc8= array1 >= array2
print(outc8)

[False  True  True]
[False  True  True]


9.2.5. Equal to

In [129]:
outc9=np.equal(array1, array2)
print(outc9)

outc10= array1 == array2
print(outc10)

[False  True False]
[False  True False]


9.2.6. Not equal to

In [130]:
outc11=np.not_equal(array1, array2)
print(outc11)

outc12= array1 != array2
print(outc12)

[ True False  True]
[ True False  True]


**10. String Functions**

10.1. add

In [131]:
str1=np.array(["I ", 16])
str2=np.array(["am", " years old."])
print(np.char.add(str1,str2))

['I am' '16 years old.']


10.2. multiply

In [132]:
str3=np.array(["J", "R", "C"])
print(np.char.multiply(str3, 5))

['JJJJJ' 'RRRRR' 'CCCCC']


10.3. capitalize

In [133]:
str4=np.array(["i", "am", "jojo"])
print(np.char.capitalize(str4))

['I' 'Am' 'Jojo']


10.4. upper and lower

In [134]:
str5=np.array(["jOmmMOjm", "faAZBk2", "jsjnKsG"])
print(np.char.upper(str5))
print(np.char.lower(str5))

['JOMMMOJM' 'FAAZBK2' 'JSJNKSG']
['jommmojm' 'faazbk2' 'jsjnksg']


10.5. join

In [135]:
str6=np.array(["Lionel", "Messi"])
print(np.char.join("?", str6))   # first argument is a specified delimeter

['L?i?o?n?e?l' 'M?e?s?s?i']


10.6. equal

In [136]:
str7=np.array(["Moin", "Servus", "Hallo"])
str8=np.array(["Tach", "Servus", "Guten Tag"])
print(np.char.equal(str7, str8))

[False  True False]


**11. Broadcasting   i**

In [4]:
broadarr1=np.array([3, 2, 1])
broadarr2=np.array([[1], [2], [3]])
sum = broadarr1 + broadarr2
print(sum)

[[4 3 2]
 [5 4 3]
 [6 5 4]]


With scalars

In [5]:
sca=np.array([1, 2, 5])
number=7
print(sca+number)

[ 8  9 12]


In [6]:
import scipy

ModuleNotFoundError: No module named 'scipy'